### ISSUE TITLE
[Feature request] Notifications for new post

### ISSUE THREAD

**Issue by lmolent** [nrobinaubertin/zusam#1]
Send email or even nicer html5 push notification (ex: https://www.home-assistant.io/components/html5/) when new message is posted.

**Comment by nrobinaubertin** [comment]
I'm working on enabling a weekly email that warns when something is new for the user at the time of sending. The idea is to get people that use Zusam to get used to actually use it.
In my experience, when someone is used to go on the service, it's not necessary to get an email for every message (since they go on it daily).

Would a weekly email be enough for your use case ?

**Comment by lmolent** [comment]
Good idea. Can it be configurable? For example daily or weekly notification for new messages?

**Comment by nrobinaubertin** [comment]
Yes, I can add the daily option (and even the monthly, let's be crazy)

**Comment by lmolent** [comment]
And when we are crazy - what about to add hourly option? ;)

**Comment by nrobinaubertin** [comment]
Okay. I propose to add that if you choose the X period, you will not be notified for messages older than 2X (so that you get at most 2 emails for the same message)

**Comment by nrobinaubertin** [comment]
Feature added for impeding 0.2
